# Generated by Django 5.1.4 on 2025-02-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenloaitaikhoan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=255)),
                ('gioitinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ngaysinh', models.DateField(blank=True, null=True)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensanpham', models.CharField(max_length=255)),
                ('hinhanh', models.ImageField(blank=True, null=True, upload_to='sanpham/')),
                ('soluong', models.PositiveIntegerField(default=0)),
                ('dongia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendanhmuc', models.CharField(max_length=255)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentruycap', models.CharField(max_length=255, unique=True)),
                ('matkhau', models.CharField(max_length=255)),
                ('hoten', models.CharField(blank=True, max_length=255, null=True)),
                ('trangthai', models.BooleanField(default=True)),
                ('maloaitaikhoan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_admin.account_type')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaylap', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('makhachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_admin.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.PositiveIntegerField()),
                ('madonhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_admin.order')),
                ('masanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_admin.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='madanhmuc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_admin.product_catalog'),
        ),
    ]
